### ISSUE TITLE
GPIO Pins

### ISSUE THREAD

**Issue by simenopsahl** [GeekMagicClock/HelloCubic-V2#7]
Can you tell me the pins used?
To help me and others installing [ESPHome](https://community.home-assistant.io/t/installing-esphome-on-geekmagic-smart-weather-clock-smalltv-pro/618029)

```yaml
# Gyro i2c MPU6050
i2c_sda_pin: GPIO??
i2c_scl_pin: GPIO??

# SPI Display
spi_clk_pin: GPIO??
spi_mosi_pin: GPIO??

# disp_cs_pin: Im guessing is not used
disp_dc_pin: GPIO??
disp_reset: GPIO??
disp_bl_pin: GPIO??
```

Is the display the same as the other models ST7789(V)?
And is it 16MB flash?
Any PSRAM?

Thanks 😁
